CREATE TABLE IF NOT EXISTS "USERS" (
    "UNIQUE_ID"  UUID         NOT NULL PRIMARY KEY,
    "USERNAME"   VARCHAR(16)  NOT NULL,
    "NICKNAME"   VARCHAR(16),
    "BALANCE"    BIGINT       NOT NULL DEFAULT 0,
    "SOCIAL_SPY" BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT "NO_DEBT" CHECK ("BALANCE" >= 0)
);

CREATE TABLE IF NOT EXISTS "MUTES" (
    "PLAYER_ID" UUID    NOT NULL PRIMARY KEY REFERENCES "USERS"("UNIQUE_ID"),
    "EXPIRES"   BIGINT
);
