CREATE TABLE IF NOT EXISTS "USERS" (
    "UNIQUE_ID"       UUID         NOT NULL PRIMARY KEY,
    "USERNAME"        VARCHAR(16)  NOT NULL,
    "NICKNAME"        VARCHAR(16),
    "BALANCE"         BIGINT       NOT NULL DEFAULT 0,
    "SOCIAL_SPY"      BOOLEAN      NOT NULL DEFAULT FALSE,
    "LAST_LOGIN_DATE" DATE,

    CONSTRAINT "NO_DEBT" CHECK ("BALANCE" >= 0),
    CONSTRAINT "VAULT_COMPAT" CHECK ("BALANCE" <= 9007199254740992)
);

CREATE TABLE IF NOT EXISTS "MUTES" (
    "PLAYER_ID" UUID    NOT NULL PRIMARY KEY REFERENCES "USERS"("UNIQUE_ID"),
    "EXPIRES"   BIGINT
);
