name: DogCore
version: 1.0.0
main: net.dumbdogdiner.dogcore.DogCorePlugin
description: Core plugin for Dumb Dog Diner
author: spazzylemons
website: https://dumbdogdiner.net/
api-version: "1.20"
depend:
  - CommandAPI
  - LuckPerms
  - ProtocolLib
  - Vault
libraries:
  - "org.postgresql:postgresql:42.6.0"
  - "org.jooq:jooq:3.18.5"
permissions:
  dogcore.back:
    description: "Allows instantly returning to where you died."
    default: true
  dogcore.craft:
    description: "Allows opening a crafting table using a command."
    default: op
  dogcore.eco:
    description: "Allows using the economy features."
    default: true
  dogcore.eco.admin:
    description: "Allows editing the balances of other players."
    default: op
  dogcore.enderchest:
    description: "Allows opening your ender chest using a command."
    default: op
  dogcore.hat:
    description: "Allows putting non-helmet blocks in your helmet slot."
    default: true
  dogcore.home:
    description: "Allows setting, deleting, and teleporting to a home."
    default: true
  dogcore.me:
    description: "Allows the /me command."
    default: true
  dogcore.mute:
    description: "Allows muting and unmuting other players."
    default: op
  dogcore.nick:
    description: "Allows changing your nickname."
    default: true
  dogcore.nick.admin:
    description: "Allows changing other players' nicknames."
    default: op
  dogcore.snoop:
    description: "Allows spying on other players."
    default: op
  dogcore.tpa:
    description: "Allows requesting teleportation."
    default: true
  dogcore.warp:
    description: "Allows warping to spawn."
    default: true
