name: DogCore
version: 1.0.0
main: net.dumbdogdiner.dogcore.DogCorePlugin
description: Core plugin for Dumb Dog Diner
author: spazzylemons
website: https://dumbdogdiner.net/
api-version: 1.19
depend:
  - CommandAPI
  - LuckPerms
permissions:
  dogcore.eco:
    description: "Allows using the economy features."
    default: true
  dogcore.eco.admin:
    description: "Allows editing the balances of other players."
    default: op
  dogcore.mute:
    description: "Allows muting and unmuting other players."
    default: op
